name: Grammar Mutator CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Valgrind
      run: |
        bash .github/workflows/setup-deps.sh
    - name: Create build directory
      run: |
        mkdir build
    - name: CMake
      run: |
        cd ./build
        cmake -DENABLE_TESTING=ON ../
    - name: Compile
      run: cmake --build build
    - name: Unit testing
      run: |
        cd ./build
        make test
    - name: Valgrind memcheck on unit testing
      run: |
        cd ./build
        make test_memcheck
